search                   : false # true, false (default)
search_full_content      : false # true, false (default)
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : ""

reCaptcha:
  siteKey                :
  secret                 :

#minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
#minimal_mistakes_skin    : "air"
#minimal_mistakes_skin    : "contrast"
#minimal_mistakes_skin    : "dark"
#minimal_mistakes_skin    : "dirt"
#minimal_mistakes_skin    : "neon"
#minimal_mistakes_skin    : "mint"
#minimal_mistakes_skin    : "sunrise"
