# Site wide configuration

url                      : ""
host                     : "0.0.0.0"

profile                  : true
future                   : true
show_drafts              : true

google_site_verification : ""
bing_site_verification   : ""
alexa_site_verification  : ""
yandex_site_verification : ""

google_ad-client         : ""
google_ad-slot           : ""
google_analytics         : ""

reCaptcha:
  siteKey: ""
  secret: ""

#minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
#minimal_mistakes_skin    : "air"
#minimal_mistakes_skin    : "contrast"
#minimal_mistakes_skin    : "dark"
#minimal_mistakes_skin    : "dirt"
#minimal_mistakes_skin    : "neon"
#minimal_mistakes_skin    : "mint"
#minimal_mistakes_skin    : "sunrise"
